pipeline {
    // agent { label 'djangonode' }
    agent any

    environment {
        DJANGO_HOST = "172.31.46.208"
        DJANGO_USER = "django_user"
        REMOTE_PATH = "/chatapp-ubuntu-22.04"
        SONAR_PROJECT_KEY = "chatapp"
        SONAR_PROJECT_NAME = "ChatApp"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Maverick1950/Jenkins_chat_app.git'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('Sonarqube') {
                    dir("${WORKSPACE}/chatapp-ubuntu-22.04") {
                        sh """
                        /home/ubuntu/jenkins/tools/hudson.plugins.sonar.SonarRunnerInstallation/SonarScanner/bin/sonar-scanner \
                        -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
                        -Dsonar.projectName=${SONAR_PROJECT_NAME} \
                        -Dsonar.sources=. \
                        -Dsonar.sourceEncoding=UTF-8
                        """
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Deploy to Django Server') {
            steps {
                sshagent(credentials: ['controller-key']) {
                    sh """
                    rsync -av --delete \
                    -e "ssh -o StrictHostKeyChecking=no" \
                    --exclude '.git' \
                    --exclude 'venv' \
                    ${WORKSPACE}/chatapp-ubuntu-22.04/ \
                    ${DJANGO_USER}@${DJANGO_HOST}:${REMOTE_PATH}/
                    """
                }
            }
        }

        stage('Run Migration') {
            steps {
                sshagent(credentials: ['controller-key']) {
                    sh """
                    ssh -o StrictHostKeyChecking=no ${DJANGO_USER}@${DJANGO_HOST} '
                        cd ${REMOTE_PATH}/fundoo &&
                        source venv/bin/activate &&
                        python manage.py migrate --noinput
                    '
                    """
                }
            }
        }

        stage('Restart Gunicorn') {
            steps {
                sshagent(credentials: ['controller-key']) {
                    sh """
                    ssh -o StrictHostKeyChecking=no ${DJANGO_USER}@${DJANGO_HOST} '
                        sudo systemctl restart gunicorn
                    '
                    """
                }
            }
        }
    }
}