pipeline {
    agent { label 'djangonode' }

    environment {
        DJANGO_HOST = "172.31.46.208"
        DJANGO_USER = "django_user"
        REMOTE_PATH = "/chatapp-ubuntu-22.04"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Maverick1950/Jenkins_chat_app.git'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('Sonarqube') {
                    sh """
                    /home/ubuntu/jenkins/tools/hudson.plugins.sonar.SonarRunnerInstallation/SonarScanner/bin/sonar-scanner
                    """
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Deploy to Django Server') {
            steps {
                sshagent(credentials: ['agent-key']) {
                    sh """
                    rsync -av --delete \
                    -e "ssh -o StrictHostKeyChecking=no" \
                    --exclude '.git' \
                    --exclude 'venv' \
                    ${WORKSPACE}/chatapp-ubuntu-22.04/ \
                    ${DJANGO_USER}@${DJANGO_HOST}:${REMOTE_PATH}/
                    """
                }
            }
        }

        stage('Run Migration') {
            steps {
                sshagent(credentials: ['agent-key']) {
                    sh """
                    ssh -o StrictHostKeyChecking=no ${DJANGO_USER}@${DJANGO_HOST} '
                        cd /chatapp-ubuntu-22.04/fundoo &&
                        source venv/bin/activate &&
                        python manage.py migrate --noinput
                    '
                    """
                }
            }
        }

        stage('Restart Gunicorn') {
            steps {
                sshagent(credentials: ['agent-key']) {
                    sh """
                    ssh -o StrictHostKeyChecking=no ${DJANGO_USER}@${DJANGO_HOST} '
                        sudo systemctl restart gunicorn
                    '
                    """
                }
            }
        }
    }
}