sonar.projectKey=chatapp
sonar.projectName=ChatApp

# IMPORTANT: run from root so '.' works properly
sonar.sources=.

sonar.sourceEncoding=UTF-8
sonar.language=py

# Python version (optional but good)
sonar.python.version=3

# Exclusions (VERY IMPORTANT for Django)
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/venv/**,**/static/**,**/media/**,**/*.js,**/*.css,**/*.html

# Optional (recommended)
sonar.test.inclusions=**/tests/**

# Coverage (if later you add pytest coverage)
# sonar.python.coverage.reportPaths=coverage.xml