sonar.projectKey=Jenkins-project
sonar.projectName=Jenkins-project

sonar.sources=fundoo
sonar.language=py

sonar.sourceEncoding=UTF-8
sonar.python.version=3

# VERY IMPORTANT: disable JS analysis completely
sonar.javascript.detectBundles=false
sonar.typescript.detectBundles=false

sonar.exclusions=**/migrations/**,**/__pycache__/**,**/venv/**,static/**,media/**,**/*.js,**/*.css,**/*.html