sonar.projectKey=chatapp
sonar.projectName=ChatApp

sonar.sources=.

sonar.sourceEncoding=UTF-8
sonar.language=py

sonar.python.version=3

sonar.exclusions=**/migrations/**,**/__pycache__/**,**/venv/**,**/static/**,**/media/**,**/*.js,**/*.css,**/*.html

sonar.test.inclusions=**/tests/**
